/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/layout/Breadcrumb.vue')['default']
    FinanceTrendChart: typeof import('./src/components/dashboard/FinanceTrendChart.vue')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    NotificationList: typeof import('./src/components/layout/NotificationList.vue')['default']
    PasswordChangeForm: typeof import('./src/components/common/PasswordChangeForm.vue')['default']
    RecentProjectsList: typeof import('./src/components/dashboard/RecentProjectsList.vue')['default']
    RecentTransactionsList: typeof import('./src/components/dashboard/RecentTransactionsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    StatCard: typeof import('./src/components/dashboard/StatCard.vue')['default']
    TodoList: typeof import('./src/components/dashboard/TodoList.vue')['default']
  }
}
