"""add_change_reason_fields

Revision ID: 64c682da040c
Revises: 816d3ccfc759
Create Date: 2025-08-25 16:41:31.866317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c682da040c'
down_revision = '816d3ccfc759'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('budget_change_reason', sa.String(length=200), nullable=True, comment='预算变更原因'))
    op.add_column('projects', sa.Column('contract_change_reason', sa.String(length=200), nullable=True, comment='合同变更原因'))
    op.add_column('projects', sa.Column('change_description', sa.Text(), nullable=True, comment='变更详细说明'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'change_description')
    op.drop_column('projects', 'contract_change_reason')
    op.drop_column('projects', 'budget_change_reason')
    # ### end Alembic commands ###
