"""add_supplier_and_created_by_fields

Revision ID: 0127c764fa7f
Revises: 1e6d1a5c5180
Create Date: 2025-08-26 12:50:36.012893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0127c764fa7f'
down_revision = '1e6d1a5c5180'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('code', sa.String(length=50), nullable=True, comment='供应商编码'))
    op.add_column('suppliers', sa.Column('business_scope', sa.Text(), nullable=True, comment='经营范围'))
    op.add_column('suppliers', sa.Column('qualification', sa.Text(), nullable=True, comment='资质证书'))
    op.alter_column('suppliers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='联系电话',
               existing_comment='电话',
               existing_nullable=True)
    op.alter_column('suppliers', 'payment_terms',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_comment='付款条件',
               existing_nullable=True)
    op.drop_constraint('uq_tenant_supplier_name', 'suppliers', type_='unique')
    op.drop_column('suppliers', 'transaction_count')
    op.drop_column('suppliers', 'total_amount')
    op.drop_column('suppliers', 'bank_info')
    op.drop_column('suppliers', 'tax_number')
    op.add_column('transactions', sa.Column('supplier_id', sa.UUID(), nullable=True, comment='关联供应商ID'))
    op.add_column('transactions', sa.Column('notes', sa.Text(), nullable=True, comment='备注'))
    op.add_column('transactions', sa.Column('attachment_url', sa.String(length=500), nullable=True, comment='附件链接'))
    op.add_column('transactions', sa.Column('reference_number', sa.String(length=100), nullable=True, comment='参考编号'))
    op.alter_column('transactions', 'id',
               existing_type=sa.UUID(),
               comment='交易ID',
               existing_comment='主键ID',
               existing_nullable=False)
    op.alter_column('transactions', 'project_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='关联项目ID',
               existing_comment='项目ID')
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment='交易金额',
               existing_comment='金额',
               existing_nullable=False)
    op.alter_column('transactions', 'currency',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_comment='货币类型',
               existing_nullable=True)
    op.alter_column('transactions', 'description',
               existing_type=sa.TEXT(),
               comment='交易描述',
               existing_comment='描述',
               existing_nullable=True)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='交易状态',
               existing_comment='状态',
               existing_nullable=True)
    op.alter_column('transactions', 'approved_by',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_comment='审批人',
               existing_nullable=True)
    op.alter_column('transactions', 'approved_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_comment='审批时间',
               existing_nullable=True)
    op.alter_column('transactions', 'created_by',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='创建人')
    op.drop_constraint('transactions_project_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_approved_by_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'suppliers', ['supplier_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'projects', ['project_id'], ['id'])
    op.drop_column('transactions', 'location')
    op.drop_column('transactions', 'supplier_info')
    op.drop_column('transactions', 'receipt_urls')
    op.drop_column('transactions', 'invoice_info')
    op.drop_column('transactions', 'amount_base')
    op.drop_column('transactions', 'approval_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('approval_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='审批状态'))
    op.add_column('transactions', sa.Column('amount_base', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False, comment='基准货币金额'))
    op.add_column('transactions', sa.Column('invoice_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='发票信息'))
    op.add_column('transactions', sa.Column('receipt_urls', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='票据图片URLs'))
    op.add_column('transactions', sa.Column('supplier_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='供应商信息'))
    op.add_column('transactions', sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='位置信息'))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_approved_by_fkey', 'transactions', 'users', ['approved_by'], ['id'])
    op.create_foreign_key('transactions_project_id_fkey', 'transactions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('transactions', 'created_by',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='创建人')
    op.alter_column('transactions', 'approved_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_comment='审批时间',
               existing_nullable=True)
    op.alter_column('transactions', 'approved_by',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_comment='审批人',
               existing_nullable=True)
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='状态',
               existing_comment='交易状态',
               existing_nullable=True)
    op.alter_column('transactions', 'description',
               existing_type=sa.TEXT(),
               comment='描述',
               existing_comment='交易描述',
               existing_nullable=True)
    op.alter_column('transactions', 'currency',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_comment='货币类型',
               existing_nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               comment='金额',
               existing_comment='交易金额',
               existing_nullable=False)
    op.alter_column('transactions', 'project_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='项目ID',
               existing_comment='关联项目ID')
    op.alter_column('transactions', 'id',
               existing_type=sa.UUID(),
               comment='主键ID',
               existing_comment='交易ID',
               existing_nullable=False)
    op.drop_column('transactions', 'reference_number')
    op.drop_column('transactions', 'attachment_url')
    op.drop_column('transactions', 'notes')
    op.drop_column('transactions', 'supplier_id')
    op.add_column('suppliers', sa.Column('tax_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='税号'))
    op.add_column('suppliers', sa.Column('bank_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='银行信息'))
    op.add_column('suppliers', sa.Column('total_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True, comment='累计交易金额'))
    op.add_column('suppliers', sa.Column('transaction_count', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='交易次数'))
    op.create_unique_constraint('uq_tenant_supplier_name', 'suppliers', ['tenant_id', 'name'])
    op.alter_column('suppliers', 'payment_terms',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_comment='付款条件',
               existing_nullable=True)
    op.alter_column('suppliers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='电话',
               existing_comment='联系电话',
               existing_nullable=True)
    op.drop_column('suppliers', 'qualification')
    op.drop_column('suppliers', 'business_scope')
    op.drop_column('suppliers', 'code')
    # ### end Alembic commands ###
