"""remove_type_field_from_categories

Revision ID: 1e6d1a5c5180
Revises: 64c682da040c
Create Date: 2025-08-26 10:45:09.043570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6d1a5c5180'
down_revision = '64c682da040c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenant_category_name_type', 'categories', type_='unique')
    op.create_unique_constraint('uq_tenant_category_name', 'categories', ['tenant_id', 'name'])
    op.drop_column('categories', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment='分类类型: income/expense'))
    op.drop_constraint('uq_tenant_category_name', 'categories', type_='unique')
    op.create_unique_constraint('uq_tenant_category_name_type', 'categories', ['tenant_id', 'name', 'type'])
    # ### end Alembic commands ###
